### PR TITLE
Update kitetail/zttp

### PR DESCRIPTION
**Pull request by arubacao**

### CODE REVIEW

**Comment by mattstauffer** [comment]
@arubacao I don't have a functioning local install to test this on at the moment--does it work fine in your experience? Thanks!

**Comment by arubacao** [comment]
Yes, I just tested it. Besides, there haven't been any breaking changes in zttp.

**Comment by mattstauffer** [comment]
Thanks @arubacao!

**Comment by arubacao** [comment]
Hey @mattstauffer , could you please also tag a new release? Cheers, Chris

**Comment by mattstauffer** [comment]
@arubacao sorry about that! https://github.com/tightenco/nova-releases/releases/tag/v0.2.3

**Comment by arubacao** [comment]
Thanks!

**Pull request merged**
